### ISSUE TITLE
Snowpack does not recognize Nunjucks template in `development` mode

### ISSUE THREAD

**Issue by x80486** [mxmul/snowpack-plugin-nunjucks#2]
Me again 👋🏻

I have the same simple project. Basically some `.njk` files in the project's root. When `snowpack dev` is executed the server starts correctly and so on, but when I browse over the exposed address (typically `http://localhost:8080`) the default entry point (`index.html`) is not recognized as HTML, but as `application/octet-stream`.

As a result, what I get is a prompt to download a file, which in turn, has the correct content (from `index.html`), but somehow it's not recognized automatically by the browsers as such.

Could it be that the integration with the plugin and Snowpack is not quite there yet, or do you think this is something that I might have misconfigured on my end — I'm quite new to Snowpack 😇

**Comment by mxmul** [comment]
Hi! I suspect that this is an issue with either Snowpack or your configuration, as the plugin API doesn't give us control over response headers.

But if you could provide a repo with a minimal reproduction case, I could take a look at it.

**Comment by x80486** [comment]
[Here](https://github.com/x80486/snowpack-nunjucks-sample) is the repository. I think this one is a little bit weird, but probably you might be able to see something there.

The setup I have is very simple, that's why I thought initially it might be an issue with the plugin, but I've seen that the `mount` setting is not straightforward some times with some configurations.

**Comment by x80486** [comment]
@mxmul, have you had any chances to look into this one?

**Comment by mxmul** [comment]
Hey @x80486 ! Sorry, I lost track of this.

The issue definitely seems to be with Snowpack's dev server. The content type is being determined based on the file extension of the underlying template, and plugins have no opportunity to override this behavior.

[Here's the relevant code in Snowpack](https://github.com/withastro/snowpack/blob/c44d86f73ac7b74507d4d5554ccb96e8b7dc5294/snowpack/src/commands/dev.ts#L672). Ideally they would treat any URL without an extension as `text/html`, but instead they look at the underlying template's file extension. Maybe they'd be open to a PR?

As a work around, you could visit `http://localhost:8080/index.html` instead of `http://localhost:8080/` in your dev environment.
